DROP TABLE TEMP5;
CREATE TABLE TEMP5(INDICE NUMBER(4), NOMBRE VARCHAR2(45));

DECLARE
	TYPE T_CLIENTE IS TABLE OF CLIENTES.NOMBRE%TYPE INDEX BY BINARY_INTEGER;
	
	TPL_CLIENTES T_CLIENTE;
	FILAS CLIENTES%ROWTYPE;
	X BINARY_INTEGER:=0;
	
BEGIN
	FOR FILAS IN(SELECT NOMBRE FROM CLIENTES)LOOP
	    X:= X+1;
	    TPL_CLIENTES(X):=FILAS.NOMBRE;
	    INSERT INTO TEMPORAL VALUES(X,TPL_CLIENTES(X));
	END LOOP;    
END;
/