DECLARE
	V_CLIENTE PEDIDOS.CODCLI%TYPE:=&CLIENTE;
	V_ID ARTICULOS.IDART%TYPE:=&ARTICULO;
	V_STOCK ARTICULOS.STOCK%TYPE;
	V_CANT NUMBER(2):=&CANTIDAD;
	V_PED NUMBER(2);
BEGIN
	SELECT STOCK INTO V_STOCK FROM ARTICULOS WHERE IDART=V_ID;
	SELECT MAX(IDPED) INTO V_PED FROM DETALLE;
	
		IF V_STOCK>V_CANT THEN
			UPDATE  ARTICULOS SET STOCK=V_STOCK-V_CANT WHERE IDART=V_ID;
			INSERT INTO TEMP(ID_ART,MENSAJE) VALUES(V_ID,'VENDIDO');
			LOOP
				V_PED:=V_PED+1;
				INSERT INTO PEDIDOS VALUES(V_PED, V_CLIENTE,SYSDATE,SYSDATE);
				INSERT INTO DETALLE VALUES(V_PED,V_ID,1);
				EXIT WHEN V_PED=15;
			END LOOP;
		ELSE
			INSERT INTO TEMP(ID_ART,MENSAJE) VALUES(V_ID,'SIN EXISTENCIAS');
			DBMS_OUTPUT.PUT_LINE('NO HAY STOCK');	
		END IF;
END;
/