DROP TABLE TEMP3;
CREATE TABLE TEMP3(COD_CLI NUMBER(2), NOMBRE_CLI VARCHAR2(15),TOT_PED NUMBER(3), PRECIO_TOT NUMBER(5));

DECLARE
	ID_CLI PEDIDOS.CODCLI%TYPE:=&CLIENTE;
	V_PED TEMP3.TOT_PED%TYPE;
	V_PRE TEMP3.PRECIO_TOT%TYPE;
	V_NOM TEMP3.NOMBRE_CLI%TYPE;
	
BEGIN

	SELECT NOMBRE INTO V_NOM FROM CLIENTES WHERE CODCLI=V_CLIENTE;
	SELECT COUNT(*) INTO V_PED FROM PEDIDOS WHERE CODCLI=V_CLIENTE;
	SELECT SUM(PRECIO*CANTIDAD) INTO V_PRE FROM PEDIDOS P, DETALLE D, ARTIDULOS A, CLIENTES C WHERE (C.CODCLI=D.CODCLI) AND (P.IDPED=D.IDPED) AND (A.IDART=D.IDART) AND C.CODCLI=ID_CLI;

	
	INSERT INTO TEMP3 VALUES(ID_CLI,V_NOM,V_PED,PRECIO_TOT);
	
END;
/
