--El enunciado no era claro y realice el ejercicio de 2 formas

-- 1-Pidiendo como datos el sueldo y comision
CREATE OR REPLACE FUNCTION ANUAL(V_SAL EMP.SAL%TYPE, V_COMM EMP.COMM%TYPE)
RETURN NUMBER
IS
SAL_ANUAL NUMBER;
BEGIN
	SELECT (V_SAL+NVL(V_COMM,0))*12 INTO SAL_ANUAL FROM DUAL;
		
	RETURN SAL_ANUAL;
END ANUAL;
/

SELECT ANUAL(1000,50) FROM DUAL;


-- 2-Pidiendo como dato el numero de empleado

CREATE OR REPLACE FUNCTION ANUAL(V_EMPNO EMP.SAL%TYPE)
RETURN NUMBER
IS
SAL_ANUAL NUMBER;
BEGIN
	SELECT (SAL+NVL(COMM,0))*12 INTO SAL_ANUAL FROM EMP WHERE EMPNO=V_EMPNO;
	
	RETURN SAL_ANUAL;
END ANUAL;
/

SELECT ANUAL(7900) FROM DUAL;