CREATE OR REPLACE TYPE VETERINARIOS AS OBJECT
(ID_VET NUMBER(2),NOM_VET VARCHAR2(20),DIR_VET VARCHAR2(25));
/

CREATE OR REPLACE TYPE MASCOTAS AS OBJECT
(ID_MASC NUMBER(2), RAZA VARCHAR2(20), NOM_MASC VARCHAR2(20),ID_VET REF VETERINARIOS);															
/
CREATE TABLE VETERINARIO OF VETERINARIOS(ID_VET PRIMARY KEY);
CREATE TABLE MASCOTA OF MASCOTAS(ID_MASC PRIMARY KEY);

--Inserta en la tabla veterinarios un registro
INSERT INTO VETERINARIO VALUES(1,'Juan Perez', 'C/ El Mareo,29');
INSERT INTO VETERINARIO VALUES(2,'Jorge María', 'C/ Marroquina,2');
--Inserta en la tabla mascotas una mascota
INSERT INTO MASCOTA VALUES(1,'PERRO','SPROKET',(SELECT REF(V) FROM VETERINARIO V WHERE V.ID_VET=1));
INSERT INTO MASCOTA VALUES(2,'GATO','OLLY',(SELECT REF(V) FROM VETERINARIO V WHERE V.ID_VET=2));
INSERT INTO MASCOTA VALUES(3,'GATO','SOMBRA',(SELECT REF(V) FROM VETERINARIO V WHERE V.ID_VET=2));
--Listar la tabla mascotas de forma que se obtenga su OID.
SELECT * FROM MASCOTA;

-- Listar los datos reales de la tabla mascota en vez de su OID.
SELECT ID_MASC, NOM_MASC, DEREF(ID_VET) FROM MASCOTA;

-- Listar el nombre y la raza de las mascotas así como el nombre de su veterinario.
SELECT NOM_MASC, RAZA, DEREF(M.ID_VET).NOM_VET FROM MASCOTA M;
			
-- Borra las tablas y los tipos
DROP TABLE MASCOTA;
DROP TABLE VETERINARIO;
DROP TYPE VETERINARIOS;
DROP TYPE MASCOTAS;